In [1]:
import numpy as np
import requests
import os
import pandas as pd
from selenium import webdriver
import time
import copy
import urllib3
from bs4 import BeautifulSoup
import re
import csv
from selenium import webdriver

In [2]:
def preprocess_match(game, team_name, fileName):
    matchID_set = [str(x) for x in range(0, 200)]
    game.rename(columns = {'Unnamed: 5':'Home_away'}, inplace = True)
    mask_home = (game['Home_away'] == '@')
    mask_away = (game['Home_away'] != '@')
    game.loc[mask_home, 'Home_away'] = 1
    game.loc[mask_away, 'Home_away'] = 0
    game = game.loc[game['G'].isin(matchID_set)]
    game = game[['G', 'Opponent', 'Home_away','Tm', 'Opp']]
    file_path = './match_data/' + team_name 
    os.makedirs(file_path, exist_ok=True)
    game.to_csv(file_path + '/' + fileName + '.csv')
def collect_match(start_year, end_year, team_name, dict_used_name):
    year_list = [str(x) for x in range(start_year, end_year)]
    for year in year_list:
        for team in dict_used_name:
            url = 'https://www.basketball-reference.com/teams/' + team +'/' + year + '_games.html'
            try:
                tb = pd.read_html(url)
                fileName = team_name +'_'+ year + '_regular'
                preprocess_match(tb[0], team_name,  fileName)
                try :
                    tb[1]
                except:
                    continue
                fileName = team_name +'_'+ year + '_playoff'
                preprocess_match(tb[1], team_name, fileName)
            except:
                continue
             
def collect_coach_id():
    coach_id = []
    res = requests.get('https://www.basketball-reference.com/coaches/NBA_stats.html/')
    regular_exp = '.*><a href="/coaches/' + charc + '/(.*)">.*'
    result = re.findall(regular_exp, res.text)
    for x in result:
        coach_id.append(x.split(".html")[0])
    file = open('./coach_data/coach_id.txt', 'w')
    for cid in coach_id:
        file.write("%s\n" % cid)
def collect_player_id():
    alphabet = [chr(i) for i in range(97,123)] 
    player_id = []
    for charc in alphabet:
        res = requests.get('https://www.basketball-reference.com/players/' + charc +'/')
        regular_exp = '.*><a href="/players/' + charc + '/(.*)">.*'
        result = re.findall(regular_exp, res.text)
        for x in result:
            player_id.append(x.split(".html")[0])
    file = open('./player_data/player_id.txt', 'w')
    for pid in player_id:
        file.write("%s\n" % pid)
def read_player_id():
    with open('./player_data/player_id.txt') as f:
        content = f.readlines()
    content = [x.strip() for x in content] 
    return content
def collect_player_basic():
    alphabet = [chr(i) for i in range(97,123)] 
    for charc in alphabet:
        if charc != 'x':
            url = 'https://www.basketball-reference.com/players/' + charc + '/'
            tb = pd.read_html(url)
            for k in range(len(tb[0]['Ht'])):
                tb[0]['Ht'][k] = str(tb[0]['Ht'][k]) + '\t'
            file_path = './player_data/basic/' 
            os.makedirs(file_path, exist_ok=True)
            tb[0].to_csv(file_path + '/' + charc + '.csv')     
def collect_player_performance():
#     player_id = read_player_id()
    file_path = './player_data/performance/regular/'
    player_id = ['abdelal01', 'abdulza01', 'abdulka01', 'abdulma02', 'abdulta01', 'abdursh01', 'abernto01', 'ablefo01', 'abramjo01', 'abrinal01',
            'bakerma01', 'jamesle01', 'bakerno01', 'bakerro01', 'bakervi01', 'baldwwa01', 'balkmre01', 'ballce01', 'balllo01', 'ballagr01', 'baltihe01', 'banksge01',
             'jacksbo01', 'jacksce01', 'jacksda01', 'jacksde01', 'jacksgr01', 'jacksja01', 'jacksje01', 'jacksji01', 'jacksjo02', 'jacksju01']
    all_tab = []
    count = 0
    for year in range(2015, 2018):
        for pid in player_id:
            
#             print('https://www.basketball-reference.com/players/' + pid[0] +'/' + str(pid) + '/gamelog/' + str(year) +'/')
            try:
                url = 'https://www.basketball-reference.com/players/' + pid[0] +'/' + str(pid) + '/gamelog/' + str(year) +'/'
                tb = pd.read_html(url)
                tb = tb[7]
                tb.insert(loc=0, column='Id', value= [pid] * len(tb))
                if count == 0:
                    all_tab = copy.deepcopy(tb)
                    count += 1
                else:
                    all_tab = all_tab.append(copy.deepcopy(tb))
                print(year, pid)
            except:
                continue
        if not all_tab.empty:
            os.makedirs(file_path, exist_ok=True)
            all_tab = all_tab.fillna(0)
            all_tab.to_csv(file_path + str(year) + '.csv')
            count = 0
        else:
            print(year, ' is empty')
        
# def collect_player_average():
#     player_id = read_player_id()
#     for pid in player_id:

In [11]:
player_id = ['jamesle01']
all_tab = []
count = 0
for year in range(1999, 2018):
    for pid in player_id:

#             print('https://www.basketball-reference.com/players/' + pid[0] +'/' + str(pid) + '/gamelog/' + str(year) +'/')
#         try:
            url = 'https://www.basketball-reference.com/players/' + pid[0] +'/' + str(pid) + '/gamelog/' + str(year) +'/'
            tb = pd.read_html(url)
            tb = tb[7]
            tb.insert(loc=0, column='Id', value= [pid] * len(tb))
            if count == 0:
                all_tab = copy.deepcopy(tb)
                count += 1
            else:
                all_tab = all_tab.append(copy.deepcopy(tb))
            print(year, pid)
    if all_tab.empty:
            os.makedirs(file_path, exist_ok=True)
            all_tab = all_tab.fillna(0)
            all_tab.to_csv(file_path + str(year) + '.csv')
            count = 0
    else:
            print(year, ' is empty')

2015 jamesle01
2015  is empty
2016 jamesle01
2016  is empty
2017 jamesle01
2017  is empty

In [15]:
collect_player_performance()

2015 jamesle01
2016 jamesle01
2017 abrinal01
2017 jamesle01
2017 bakerro01
2017 baldwwa01
2017 jacksde01

In [11]:
# collect_player_performance()
# https://www.basketball-reference.com/players/c/curryst01.html
player_id = read_player_id()
count = 0
for pid in player_id:
    try:
        url = 'https://www.basketball-reference.com/players/'+pid[0]+'/'+pid+'.html'
        tb = pd.read_html(url)
        col_ct = 0
        lst = (list(tb[0])[0:30])
        for it in lst:
            if it.split(':')[0] != 'Unnamed':
                col_ct += 1
            else:
                break
        tb = tb[0][list(tb[0])[0:col_ct]]
        tb.insert(loc=0, column='Id', value= [pid] * len(tb['Season']))
        tb = tb[0:-1]
        if count == 0:
            all_tab = copy.deepcopy(tb)
            count += 1
        else:
            all_tab = all_tab.append(copy.deepcopy(tb))
        print(pid)
    except:
        continue
all_tab = all_tab.fillna(0)
all_tab.to_csv('player_perform_avg.csv')

abdelal01

In [10]:
all_tab = all_tab.fillna(0)
all_tab['3P%']

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
Name: 3P%, dtype: float64

In [3]:
dict_used_name = {}
dict_used_name['ATL'] = ['ATL','STL', 'MLH']
dict_used_name['BOS'] = ['BOS']
dict_used_name['BRK'] = ['BRK', 'NJN', 'NYN','NJA','NYA']
dict_used_name['CHO'] = ['CHO','CHH','CHA']
dict_used_name['CHI'] = ['CHI']
dict_used_name['CLE'] = ['CLE']
dict_used_name['DAL'] = ['DAL']
dict_used_name['DEN'] = ['DEN', 'DNR','DNA']
dict_used_name['DET'] = ['DET', 'FTW']
dict_used_name['GSW'] = ['GSW', 'SFW', 'PHW']
dict_used_name['HOU'] = ['HOU', 'SDR']
dict_used_name['IND'] = ['IND', 'INA']
dict_used_name['LAC'] = ['LAC', 'SDC', 'BUF']
dict_used_name['LAL'] = ['LAL', 'MNL']
dict_used_name['MEM'] = ['MEM', 'VAN']
dict_used_name['MIA'] = ['MIA']
dict_used_name['MIL'] = ['MIL']
dict_used_name['MIN'] = ['MIN']
dict_used_name['NOP'] = ['NOP', 'NOK','NOH']
dict_used_name['NYK'] = ['NYK']
dict_used_name['OKC'] = ['SEA', 'OKC']
dict_used_name['ORL'] = ['ORL']
dict_used_name['PHI'] = ['PHI', 'SYR']
dict_used_name['PHO'] = ['PHO']
dict_used_name['POR'] = ['POR']
dict_used_name['SAS'] = ['SAS', 'DLC', 'TEX', 'SAA']
dict_used_name['SAC'] = ['SAC', 'KCK','KCO','CIN','ROC']
dict_used_name['TOR'] = ['TOR']
dict_used_name['UTA'] = ['UTA', 'NOJ']
dict_used_name['WAS'] = ['WAS', 'WSB','CAP','BAL','CHZ','CHP']
team_name_list = ['ATL', 'BOS', 'BRK', 'CHO', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 
                  'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 
                  'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAS', 'SAC', 'TOR', 'UTA', 'WAS']

In [6]:
count = 0
for k in team_name_list:
#     all_tb = pd.DataFrame()
    for year in range(2016, 2017):
        for term in ['playoff', 'regular']:
            try:
                FileName = (k + '_' + str(year) + '_' + term)
                dfm = pd.read_csv('./match_data/' + k + '/' + FileName + '.csv', encoding="ISO-8859-1")
#                 print(dfm.columns.get_values().tolist())
                dfm.insert(loc=0, column='year', value= [year] * len(tb))
                dfm.insert(loc=0, column='team', value= [k] * len(tb))
                dfm.insert(loc=0, column='playoff_regualr', value= [term] * len(tb))
                if count == 0:
                    all_tb = dfm
                else:
                    all_tb.append(copy.deepcopy(dfm))
            except:
                continue
    all_tb.to_csv('./match_data/' + k +'.csv')
    count = 0

In [36]:
pid_list = read_player_id()

In [9]:
collect_player_basic()

/Users/zhoutongjiang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [81]:

driver = webdriver.Chrome()
driver.get('https://www.basketball-reference.com/players/z/zellety01/gamelog/2017/')
soup = BeautifulSoup(driver.page_source,'lxml')
driver.quit()
table = soup.find_all('table')[-1]  #This is the index of any table of that page. If you change it you can get different tables.
# print(table[])
tab_data = [[celldata.text for celldata in rowdata.find_all(["th","td"])]
                        for rowdata in table.find_all("tr")]

with open("./player_data/performance/test.csv",'w') as resultFile:
    wr = csv.writer(resultFile, dialect='excel')
    for k in tab_data:
        wr.writerow(k)

Rk G Date Age Tm   Opp   GS MP FG FGA FG% 3P 3PA 3P% FT FTA FT% ORB DRB TRB AST STL BLK TOV PF PTS GmSc +/-
1 1 2017-04-16 27-089 BOS  CHI L (-4) 0 3:03 0 1 .000 0 0  0 0  1 1 2 0 0 0 0 1 0 -0.1 +1
2 2 2017-04-18 27-091 BOS  CHI L (-14) 0 8:39 2 2 1.000 0 0  0 0  1 0 1 0 0 0 1 0 4 3.1 +1
3  2017-04-21 27-094 BOS @ CHI W (+17) Did Not Play
4  2017-04-23 27-096 BOS @ CHI W (+9) Did Not Play
5  2017-04-26 27-099 BOS  CHI W (+11) Did Not Play
6 3 2017-04-28 27-101 BOS @ CHI W (+22) 0 5:09 0 1 .000 0 0  0 0  0 2 2 0 0 0 0 0 0 -0.1 -5
7  2017-04-30 27-103 BOS  WAS W (+12) Did Not Play
8  2017-05-02 27-105 BOS  WAS W (+10) Did Not Play
9 4 2017-05-04 27-107 BOS @ WAS L (-27) 0 10:34 0 3 .000 0 0  3 4 .750 0 4 4 1 0 0 0 1 3 2.0 -6
10 5 2017-05-07 27-110 BOS @ WAS L (-19) 0 5:27 2 3 .667 0 0  0 0  0 0 0 1 0 0 0 1 4 3.0 +3
11 6 2017-05-10 27-113 BOS  WAS W (+22) 0 4:21 2 5 .400 0 0  2 2 1.000 2 0 2 0 0 0 0 1 6 4.3 -2
12  2017-05-12 27-115 BOS @ WAS L (-1) Did Not Play
13  2017-05-15 27-118 BOS  WAS W (+10) Did Not Play
14 7 2017-05-17 27-120 BOS  CLE L (-13) 0 5:07 1 1 1.000 0 0  1 2 .500 0 0 0 1 0 0 0 1 3 2.6 -3
15 8 2017-05-19 27-122 BOS  CLE L (-44) 0 14:14 4 6 .667 0 0  0 0  2 2 4 0 0 1 2 1 8 5.7 -1
16 9 2017-05-21 27-124 BOS @ CLE W (+3) 0 7:23 0 0  0 0  0 0  1 0 1 3 0 0 0 0 0 2.8 -4
17 10 2017-05-23 27-126 BOS @ CLE L (-13) 0 2:12 0 0  0 0  0 0  0 0 0 0 0 0 0 0 0 0.0 -5
18 11 2017-05-25 27-128 BOS  CLE L (-33) 0 12:00 2 3 .667 0 0  0 0  1 2 3 2 0 1 1 1 4 4.7 +2

In [33]:
# options.add_argument("--test-type")
# options.binary_location = "/usr/bin/chromium"
# # driver = webdriver.Chrome()
# driver.get('https://www.basketball-reference.com/players/a/')

In [34]:
# driver = webdriver.Chrome()

In [2]:
# file_path = './team_data/' + 'AHL'
# print(file_path)
# os.makedirs(file_path)

In [3]:
url = 'https://www.basketball-reference.com/players/z/zellety01/gamelog/2017/#pgl_basic_playoffs::none'
tb = pd.read_html(url)

,Rk,G,Date,Age,Tm,,Opp,.1,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
0,1,1,2016-10-26,26-283,BOS,NaN,BRK,W (+5),0,16:26,...,2,4,3,0,2,1,2,13,13.8,-8
1,2,2,2016-10-27,26-284,BOS,@,CHI,L (-6),0,20:18,...,4,5,1,0,2,1,3,6,2.3,+2
2,3,3,2016-10-29,26-286,BOS,@,CHO,W (+6),0,12:04,...,4,4,1,0,1,0,3,2,3.1,-4
3,4,4,2016-11-02,26-290,BOS,NaN,CHI,W (+7),1,24:45,...,1,4,0,1,0,0,3,11,7.1,+9
4,5,5,2016-11-03,26-291,BOS,@,CLE,L (-6),1,27:46,...,7,10,6,0,2,0,3,11,15.6,-7
5,6,6,2016-11-06,26-294,BOS,NaN,DEN,L (-16),1,25:46,...,5,5,2,1,1,1,5,6,3.9,-12
6,7,7,2016-11-09,26-297,BOS,@,WAS,L (-25),1,14:18,...,1,2,1,0,1,0,0,6,6.8,-6
7,8,8,2016-11-11,26-299,BOS,NaN,NYK,W (+28),0,20:49,...,3,4,0,2,1,3,4,11,6.9,+15
8,9,9,2016-11-12,26-300,BOS,@,IND,W (+6),0,15:46,...,2,6,0,0,1,0,0,7,7.7,+7
9,10,10,2016-11-14,26-302,BOS,@,NOP,L (-1),0,5:07,...,0,0,1,0,0,0,0,0,-0.7,-7
10,11,11,2016-11-16,26-304,BOS,NaN,DAL,W (+7),0,8:24,...,2,4,0,0,0,0,0,4,2.6,0
11,12,12,2016-11-18,26-306,BOS,NaN,GSW,L (-16),0,23:22,...,4,7,2,0,0,2,1,5,3.5,+11
12,13,13,2016-11-19,26-307,BOS,@,DET,W (+2),0,3:41,...,0,1,0,0,0,0,0,2,1.0,-1
13,14,14,2016-11-21,26-309,BOS,@,MIN,W (+6),0,8:41,...,3,3,1,0,0,0,1,2,2.9,-3
14,15,15,2016-11-23,26-311,BOS,@,BRK,W (+19),0,7:52,...,3,4,0,0,2,0,1,2,3.6,+9
15,16,16,2016-11-25,26-313,BOS,NaN,SAS,L (-6),0,2:17,...,0,0,0,0,0,0,0,0,0.0,-1
16,17,17,2016-11-28,26-316,BOS,@,MIA,W (+8),1,25:20,...,4,7,2,0,1,1,4,10,9.5,+1
17,18,18,2016-11-30,26-318,BOS,NaN,DET,L (-7),0,4:57,...,0,1,0,0,0,0,2,1,0.5,-1
18,19,19,2016-12-02,26-320,BOS,NaN,SAC,W (+5),0,4:08,...,0,1,0,0,0,1,0,0,-1.0,-9
19,20,20,2016-12-03,26-321,BOS,@,PHI,W (+1),0,3:46,...,0,0,0,0,0,0,1,0,-0.4,+1
20,Rk,G,Date,Age,Tm,NaN,Opp,NaN,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
21,21,NaN,2016-12-05,26-323,BOS,@,HOU,L (-1),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,21,2016-12-07,26-325,BOS,@,ORL,W (+30),0,7:09,...,1,1,1,1,1,0,0,0,2.0,+2
23,23,22,2016-12-09,26-327,BOS,NaN,TOR,L (-7),0,5:29,...,2,3,1,0,0,0,0,0,-0.1,-1
24,24,NaN,2016-12-11,26-329,BOS,@,OKC,L (-3),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,23,2016-12-14,26-332,BOS,@,SAS,L (-7),0,11:32,...,1,1,2,0,0,0,0,2,2.0,0
26,26,NaN,2016-12-16,26-334,BOS,NaN,CHO,W (+8),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,24,2016-12-18,26-336,BOS,@,MIA,W (+10),0,3:57,...,1,1,0,0,0,0,0,0,-1.1,+2
28,28,NaN,2016-12-20,26-338,BOS,@,MEM,W (+3),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,NaN,2016-12-22,26-340,BOS,@,IND,W (+7),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,55,NaN,2017-02-13,27-027,BOS,@,DAL,W (+13),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,56,34,2017-02-15,27-029,BOS,NaN,PHI,W (+8),0,8:45,...,2,2,1,0,0,1,1,2,1.6,-7
58,57,35,2017-02-16,27-030,BOS,@,CHI,L (-1),0,8:50,...,0,0,4,0,0,0,0,4,6.2,+3
59,58,NaN,2017-02-24,27-038,BOS,@,TOR,L (-10),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,59,36,2017-02-26,27-040,BOS,@,DET,W (+6),0,3:51,...,0,0,0,0,0,0,1,0,-0.4,-1
61,60,37,2017-02-27,27-041,BOS,NaN,ATL,L (-16),0,8:42,...,0,1,2,0,1,0,1,5,6.8,+1
62,Rk,G,Date,Age,Tm,NaN,Opp,NaN,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
63,61,38,2017-03-01,27-043,BOS,NaN,CLE,W (+4),0,4:32,...,0,0,0,1,0,0,0,0,0.3,-4
64,62,NaN,2017-03-03,27-045,BOS,@,LAL,W (+20),Inactive,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,63,39,2017-03-05,27-047,BOS,@,PHO,L (-3),0,5:31,...,4,5,0,0,0,3,2,0,-2.6,0
66,64,40,2017-03-06,27-048,BOS,@,LAC,L (-14),0,6:26,...,1,1,1,0,0,0,3,0,-0.2,-2
67,65,41,2017-03-08,27-050,BOS,@,GSW,W (+13),0,0:45,...,0,0,0,0,0,0,0,0,0.0,-2
68,66,42,2017-03-10,27-052,BOS,@,DEN,L (-20),0,1:58,...,0,0,0,0,0,0,0,2,1.7,-3
69,67,NaN,2017-03-12,27-054,BOS,NaN,CHI,W (+20),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,68,NaN,2017-03-15,27-057,BOS,NaN,MIN,W (+13),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,69,43,2017-03-17,27-059,BOS,@,BRK,W (+3),0,7:00,...,1,1,0,0,0,0,2,3,1.8,-5
72,70,NaN,2017-03-19,27-061,BOS,@,PHI,L (-6),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,71,44,2017-03-20,27-062,BOS,NaN,WAS,W (+8),0,6:26,...,1,3,0,0,0,0,0,4,3.7,-4
74,72,45,2017-03-22,27-064,BOS,NaN,IND,W (+9),0,10:15,...,3,3,2,0,1,0,2,6,5.5,+8
75,73,46,2017-03-24,27-066,BOS,NaN,PHO,W (+10),0,11:27,...,0,0,1,0,1,2,2,0,-4.3,-8
76,74,NaN,2017-03-26,27-068,BOS,NaN,MIA,W (+4),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,75,47,2017-03-29,27-071,BOS,NaN,MIL,L (-3),0,7:35,...,1,2,1,0,0,0,2,7,5.6,+8
78,76,NaN,2017-03-31,27-073,BOS,NaN,ORL,W (+1),Did Not Play,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,77,48,2017-04-02,27-075,BOS,@,NYK,W (+16),0,8:58,...,2,2,0,0,0,1,2,3,1.1,-9
80,78,NaN,2017-04-05,27-078,BOS,NaN,CLE,L (-23),Inactive,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,79,NaN,2017-04-06,27-079,BOS,@,ATL,L (-7),Inactive,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,80,49,2017-04-08,27-081,BOS,@,CHO,W (+7),0,9:19,...,2,2,2,0,0,0,0,2,3.7,-1
83,Rk,G,Date,Age,Tm,NaN,Opp,NaN,GS,MP,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-
84,81,50,2017-04-10,27-083,BOS,NaN,BRK,W (+9),0,7:29,...,0,0,0,0,0,0,0,4,3.0,-8
85,82,51,2017-04-12,27-085,BOS,NaN,MIL,W (+18),0,10:51,...,1,2,0,0,0,0,0,5,3.6,-4

In [3]:
# import urllib.request
with urllib.request.urlopen("https://www.basketball-reference.com/players/z/zellety01/gamelog/2017/") as url:
    html_text = url.read()
# print(html_text)
from bs4 import BeautifulSoup, Comment
soup = BeautifulSoup(html_text, 'lxml')
comments = soup.findAll(text=lambda text:isinstance(text, Comment))
[comment.extract() for comment in comments]

NameError: name 'urllib' is not defined

In [60]:
type(html_text)

bytes

In [4]:
alphabet = [chr(i) for i in range(97,98)] 
for charc in alphabet:
    if charc != 'x':
        url = 'https://www.basketball-reference.com/players/' + charc + '/'
        tb = pd.read_html(url)
        for k in range(len(tb[0]['Ht'])):
            tb[0]['Ht'][k] = str(tb[0]['Ht'][k]) + '\t'
        file_path = './player_data/basic/' 
        os.makedirs(file_path, exist_ok=True)
        tb[0].to_csv(file_path + '/' + charc + '.csv')

/Users/zhoutongjiang/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [5]:
url = 'https://www.basketball-reference.com/players/' + 'a' + '/'
tb = pd.read_html(url)

In [6]:
tb

[                   Player  From    To  Pos    Ht   Wt          Birth Date  \
 0          Alaa Abdelnaby  1991  1995  F-C  6-10  240       June 24, 1968
 1         Zaid Abdul-Aziz  1969  1978  C-F   6-9  235       April 7, 1946
 2    Kareem Abdul-Jabbar*  1970  1989    C   7-2  225      April 16, 1947
 3      Mahmoud Abdul-Rauf  1991  2001    G   6-1  162       March 9, 1969
 4       Tariq Abdul-Wahad  1998  2003    F   6-6  223    November 3, 1974
 5     Shareef Abdur-Rahim  1997  2008    F   6-9  225   December 11, 1976
 6           Tom Abernethy  1977  1981    F   6-7  220         May 6, 1954
 7             Forest Able  1957  1957    G   6-3  180       July 27, 1932
 8          John Abramovic  1947  1948    F   6-3  195    February 9, 1919
 9            Alex Abrines  2017  2018  G-F   6-6  190      August 1, 1993
 10             Alex Acker  2006  2009    G   6-5  185    January 21, 1983
 11           Don Ackerman  1954  1954    G   6-0  183   September 4, 1930
 12             Mark Acres  1988  1993  F-C  6-11  220   November 15, 1962
 13              Bud Acton  1968  1968    F   6-6  210    January 11, 1942
 14             Quincy Acy  2013  2018    F   6-7  240     October 6, 1990
 15            Alvan Adams  1976  1988  C-F   6-9  210       July 19, 1954
 16              Don Adams  1971  1977    F   6-6  210   November 27, 1947
 17           George Adams  1973  1975  F-G   6-5  210        May 15, 1949
 18           Hassan Adams  2007  2009    G   6-4  220       June 20, 1984
 19           Jordan Adams  2015  2016    G   6-5  209        July 8, 1994
 20          Michael Adams  1986  1996    G  5-10  162    January 19, 1963
 21           Steven Adams  2014  2018    C   7-0  255       July 20, 1993
 22         Rafael Addison  1987  1997  F-G   6-7  215       July 22, 1964
 23            Bam Adebayo  2018  2018  C-F  6-10  243       July 18, 1997
 24           Rick Adelman  1969  1975    G   6-1  175       June 16, 1946
 25            Jeff Adrien  2011  2015    F   6-7  245   February 10, 1986
 26          Arron Afflalo  2008  2018    G   6-5  210    October 15, 1985
 27           Maurice Ager  2007  2011    G   6-5  202    February 9, 1984
 28           Mark Aguirre  1982  1994  F-G   6-6  232   December 10, 1959
 29           Blake Ahearn  2008  2012    G   6-2  190        May 27, 1984
 ..                    ...   ...   ...  ...   ...  ...                 ...
 128      Hilton Armstrong  2007  2014  F-C  6-11  235   November 11, 1984
 129        Tate Armstrong  1978  1979    G   6-3  175     October 5, 1955
 130         Jesse Arnelle  1956  1956    F   6-5  220   December 30, 1933
 131           Jay Arnette  1964  1966    G   6-2  175   December 19, 1938
 132            Bob Arnzen  1970  1974    F   6-5  205    November 3, 1947
 133         Carlos Arroyo  2002  2011    G   6-2  202       July 30, 1979
 134        Darrell Arthur  2009  2018    F   6-9  235      March 25, 1988
 135          John Arthurs  1970  1970    G   6-4  185     August 15, 1947
 136           Jamel Artis  2018  2018  G-F   6-7  213    January 12, 1993
 137             Omer Asik  2011  2018    C   7-0  255        July 4, 1986
 138         Vincent Askew  1988  1998  G-F   6-6  210   February 28, 1966
 139          Keith Askins  1991  1999  G-F   6-7  197   December 15, 1967
 140           Don Asmonga  1954  1954    G   6-2  185   February 15, 1928
 141             Dick Atha  1956  1958    G   6-2  190  September 21, 1931
 142         Chucky Atkins  2000  2010    G  5-11  160     August 14, 1974
 143             Al Attles  1961  1971    G   6-0  175    November 7, 1936
 144         Chet Aubuchon  1947  1947    G  5-10  137        May 18, 1916
 145         Stacey Augmon  1992  2006  F-G   6-8  205      August 1, 1968
 146         D.J. Augustin  2009  2018    G   6-0  183   November 10, 1987
 147       James Augustine  2007  2008    F  6-10  235   February 27, 1984
 148          Isaac Austin  1992  2002    C  6-10  255     August 18, 1969
 149         Johnny Austin  1967  1968    G   6-0  170     August 31, 1944
 150            Ken Austin  1984  1984    F   6-9  205       July 15, 1961
 151         Anthony Avent  1993  2000    F   6-9  235    October 18, 1969
 152          Bird Averitt  1974  1978    G   6-1  170       July 22, 1952
 153         William Avery  2000  2002    G   6-2  197      August 8, 1979
 154         Dennis Awtrey  1971  1982    C  6-10  235   February 22, 1948
 155          Gustavo Ayon  2012  2014    C  6-10  250       April 1, 1985
 156            Jeff Ayres  2010  2016    F   6-9  240      April 29, 1987
 157      Kelenna Azubuike  2007  2012    G   6-5  220   December 16, 1983

                                               Colleges
 0                                      Duke University
 1                                Iowa State University
 2                University of California, Los Angeles
 3                           Louisiana State University
 4    University of Michigan, San Jose State University
 5                             University of California
 6                                   Indiana University
 7                          Western Kentucky University
 8                       Salem International University
 9                                                  NaN
 10                               Pepperdine University
 11                              Long Island University
 12                             Oral Roberts University
 13                                   Hillsdale College
 14                                   Baylor University
 15                              University of Oklahoma
 16                             Northwestern University
 17                             Gardner-Webb University
 18                               University of Arizona
 19               University of California, Los Angeles
 20                                      Boston College
 21                            University of Pittsburgh
 22                                 Syracuse University
 23                              University of Kentucky
 24                         Loyola Marymount University
 25                           University of Connecticut
 26               University of California, Los Angeles
 27                           Michigan State University
 28                                   DePaul University
 29                           Missouri State University
 ..                                                 ...
 128                          University of Connecticut
 129                                    Duke University
 130                      Pennsylvania State University
 131                      University of Texas at Austin
 132                           University of Notre Dame
 133                   Florida International University
 134                               University of Kansas
 135                                  Tulane University
 136                           University of Pittsburgh
 137                                                NaN
 138                              University of Memphis
 139                              University of Alabama
 140                                   Alliance College
 141                           Indiana State University
 142                        University of South Florida
 143  North Carolina Agricultural and Technical Stat...
 144                          Michigan State University
 145                    University of Nevada, Las Vegas
 146                      University of Texas at Austin
 147         University of Illinois at Urbana-Champaign
 148                           Arizona State University
 149                                     Boston College
 150                                    Rice University
 151                              Seton Hall University
 152                              Pepperdine University
 153                                    Duke University
 154                             Santa Clara University
 155                                                NaN
 156                           Arizona State University
 157                             University of Kentucky

 [158 rows x 8 columns]]